#! /bin/bash -
if [ -n "$1" ]; then
  if [[ "$1" = "--help" ]] || [[ "$1" = "-h" ]]; then
    echo "--dir              show where notes are stored"
    echo "-y, --yesterday    shows yesterdays note"
    echo "--ls               shows all notes"
    echo "-h, --help         shows all commands"
    echo "-d, --daysago      shows notes from x days ago. Example: \"--daysago 2\""
    exit;
  fi

  if [[ "$1" = "--dir" ]]; then
    echo "$(dirname ~/.bnote)/.bnote"
    exit
  fi

  if [[ "$1" = "--yesterday" ]] || [[ "$1" = "-y" ]]; then
    yesterday=$(date -r `expr \`date +%s\` - 86400` '+%Y_%m_%d')
    less ~/.bnote/$yesterday.txt
    exit
  fi

  if [[ "$1" = "--daysago" ]] || [[ "$1" = "-d" ]]; then
    let daysInMs="86400*$2"
    ms="$b$daysInMs"
    dte=$(date -r `expr \`date +%s\` - $ms` '+%Y_%m_%d')
    less ~/.bnote/$dte.txt
    exit
  fi

  if [[ "$1" = "--ls" ]]; then
    ls ~/.bnote
    exit
  fi

  less ~/.bnote/$1.txt
  exit
fi

mkdir -p ~/.bnote/;

date=$(date +'%Y_%m_%d')
time=$(date +"%T")
filename="$date.txt"

if [[ ! -e ~/.bnote/$filename ]]; then
  echo "----------------------" > ~/.bnote/$filename
  echo "--- ${date} log ---" >> ~/.bnote/$filename
  echo "----------------------" >> ~/.bnote/$filename
fi

echo "" >> ~/.bnote/$filename
echo "---" >> ~/.bnote/$filename
echo "$time" >> ~/.bnote/$filename
echo "---" >> ~/.bnote/$filename
vim '+normal Go' ~/.bnote/$filename
