#! /bin/bash -
if [ -n "$1" ]; then
  if [[ "$1" = "--help" ]]; then
    echo "--dir show where notes are stored"
    echo "--yesterday shows yesterdays note"
    echo "--ls shows all notes"
    echo "--help shows all commands"
    echo "--daysago 2" shows notes from x days ago
    exit;
  fi

  if [[ "$1" = "--dir" ]]; then
    echo "$(dirname ~/.bnote)/.bnote"
    exit
  fi

  if [[ "$1" = "--yesterday" ]]; then
    yesterday=$(date -r `expr \`date +%s\` - 86400` '+%Y_%m_%d')
    less ~/.bnote/$yesterday.txt
    exit
  fi

  if [[ "$1" = "--daysago" ]]; then
    let daysInMs="86400*$2"
    ms="$b$daysInMs"
    dte=$(date -r `expr \`date +%s\` - $ms` '+%Y_%m_%d')
    less ~/.bnote/$dte.txt
    exit
  fi

  if [[ "$1" = "--ls" ]]; then
    ls ~/.bnote
    exit
  fi

  less ~/.bnote/$1.txt
  exit
fi

mkdir -p ~/.bnote/;

date=$(date +'%Y_%m_%d')
time=$(date +"%T")
filename="$date.txt"

if [[ ! -e ~/.bnote/$filename ]]; then
  echo "----------------------" > ~/.bnote/$filename
  echo "--- ${date} log ---" >> ~/.bnote/$filename
  echo "----------------------" >> ~/.bnote/$filename
fi

echo "" >> ~/.bnote/$filename
echo "---" >> ~/.bnote/$filename
echo "$time" >> ~/.bnote/$filename
echo "---" >> ~/.bnote/$filename
vim '+normal Go' ~/.bnote/$filename
